# Generated by Django 3.1.5 on 2021-01-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma_points', models.IntegerField()),
            ],
            options={
                'verbose_name': 'karma_points',
                'verbose_name_plural': 'karma_points',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('ratings_type', models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], default='0', max_length=256)),
            ],
            options={
                'verbose_name': 'ratings',
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'userid',
                'verbose_name_plural': 'userid',
            },
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_id', models.IntegerField()),
                ('username_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'username',
                'verbose_name_plural': 'username',
            },
        ),
    ]
